name: todo_hive
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  hive_flutter:
  flutter_slidable:
  cupertino_icons: ^1.0.4
  date_format:
  flutter_local_notifications: ^9.7.0
  flutter_native_timezone:
  flutter_svg:
  font_awesome_flutter:
  get:
  get_storage:
  hive:
  intl:
  lottie:
  path_provider:
  timezone:

  android_alarm_manager_plus:
  animations:
  auto_size_text:
  build_runner:
  delayed_display:
  floating_bottom_navigation_bar:
  floating_navbar:

  flutter_markdown:

  flutter_point_tab_bar:
  fluttertoast:
  google_fonts:

  hive_generator:
  oktoast:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lottie/
    - assets/images/
